version: '3.8'
services:
  db:
    image: postgres:15
    container_name: spend-sync-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spend-sync
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  db_data:
    name: spend-sync-data

